const creatures = [
  {
    id: 1,
    name: "Demon",
    price: 50,
    hp: 60,
    attack: 50,
    attackName: "Slash",
    attackType: "Normal",
    speed: 60,
    defense: 20,
    critical: 25,
  },
  {
    id: 2,
    name: "Medusa",
    price: 50,
    hp: 110,
    attack: 30,
    attackName: "Gaze",
    attackType: "Magic",
    speed: 30,
    defense: 15,
    critical: 15,
  },
  {
    id: 3,
    name: "Baby Dragon",
    price: 50,
    hp: 60,
    attack: 50,
    attackName: "Exhale",
    attackType: "Magic",
    speed: 60,
    defense: 20,
    critical: 25,
  },
  {
    id: 4,
    name: "Lizard",
    price: 50,
    hp: 110,
    attack: 30,
    attackName: "Impale",
    attackType: "Normal",
    speed: 30,
    defense: 15,
    critical: 15,
  },
];

module.exports = creatures;
