const creatures = [
  {
    id: 1,
    name: "Demon",
    price: 50,
    hp: 60,
    attack: 50,
    attackName: "Slash",
    attackType: "Normal",
    speed: 60,
    defense: 20,
    critical: 25,
    mp: 100,
    mpRegen: 25,
    special: 75,
    specialCost: 100,
    specialName: "Harvest",
    specialType: "Lifesteal",
    special2: 75,
    specialCost2: 100,
    specialName2: "Sunder",
    specialType2: "Magic",
  },
  {
    id: 2,
    name: "Medusa",
    price: 50,
    hp: 110,
    attack: 30,
    attackName: "Gaze",
    attackType: "Magic",
    speed: 30,
    defense: 15,
    critical: 15,
    mp: 100,
    mpRegen: 25,
    special: 75,
    specialCost: 100,
    specialName: "Petrify",
    specialType: "Magic",
    special2: 75,
    specialCost2: 100,
    specialName2: "Entrance",
    specialType2: "Lifesteal",
  },
  {
    id: 3,
    name: "Baby Dragon",
    price: 50,
    hp: 60,
    attack: 50,
    attackName: "Exhale",
    attackType: "Magic",
    speed: 60,
    defense: 20,
    critical: 25,
    mp: 100,
    mpRegen: 25,
    special: 75,
    specialCost: 100,
    specialName: "Fireball",
    specialType: "Magic",
    special2: 75,
    specialCost2: 100,
    specialName2: "Spit",
    specialType2: "Poison",
  },
  {
    id: 4,
    name: "Lizard",
    price: 50,
    hp: 110,
    attack: 30,
    attackName: "Impale",
    attackType: "Normal",
    speed: 30,
    defense: 15,
    critical: 15,
    mp: 100,
    mpRegen: 25,
    special: 75,
    specialCost: 100,
    specialName: "Inject",
    specialType: "Poison",
    special2: 75,
    specialCost2: 100,
    specialName2: "Foresight",
    specialType2: "Magic",
  },
  {
    id: 5,
    name: "Ice Golem",
    price: 50,
    hp: 110,
    attack: 30,
    attackName: "Slice",
    attackType: "Magic",
    speed: 30,
    defense: 15,
    critical: 15,
    mp: 100,
    mpRegen: 25,
    special: 75,
    specialCost: 100,
    specialName: "Ice Cloak",
    specialType: "Heal",
    special2: 75,
    specialCost2: 100,
    specialName2: "Ice Bomb",
    specialType2: "Magic",
  },
  {
    id: 6,
    name: "Nuclear Golem",
    price: 500,
    hp: 60,
    attack: 50,
    attackName: "Slice",
    attackType: "Magic",
    speed: 60,
    defense: 20,
    critical: 25,
    mp: 100,
    mpRegen: 25,
    special: 37.5,
    specialCost: 50,
    specialName: "Mutate",
    specialType: "Lifesteal",
    special2: 75,
    specialCost2: 100,
    specialName2: "Radiate",
    specialType2: "Magic",
  },
  {
    id: 7,
    name: "Quantum Golem",
    price: 500,
    hp: 60,
    attack: 50,
    attackName: "Slice",
    attackType: "Magic",
    speed: 60,
    defense: 20,
    critical: 25,
    mp: 100,
    mpRegen: 25,
    special: 37.5,
    specialCost: 50,
    specialName: "Phase Shift",
    specialType: "Heal",
    special2: 75,
    specialCost2: 100,
    specialName2: "Entangle",
    specialType2: "Lifesteal",
  },
];

module.exports = creatures;
